### ISSUE TITLE
Azure Encrypt error 404

### ISSUE THREAD

**Issue by asc-adean** [VirtusLab/crypt#10]
`echo "This_is_A_secret" | ./crypt encrypt azure --vaultURL https://XXXX.vault.azure.net --name testsecret --version 8dc4f7c4-046d-401b-88c6-7467d4680764`
```
ERROR: keyvault.BaseClient#Encrypt: Failure responding to request: StatusCode=404 -- Original Error: autorest/azure: error response cannot be parsed: "<!DOCTYPE html PUBLIC \"-//W3C//DTD XHTML 1.0 Strict//EN\" \"http://www.w3.org/TR/xhtml1/DTD/xhtml1-strict.dtd\">\r\n<html xmlns=\"http://www.w3.org/1999/xhtml\">\r\n<head>\r\n<meta http-equiv=\"Content-Type\" content=\"text/html; charset=iso-8859-1\"/>\r\n<title>404 - File or directory not found.</title>\r\n<style type=\"text/css\">\r\n<!--\r\nbody{margin:0;font-size:.7em;font-family:Verdana, Arial, Helvetica, sans-serif;background:#EEEEEE;}\r\nfieldset{padding:0 15px 10px 15px;} \r\nh1{font-size:2.4em;margin:0;color:#FFF;}\r\nh2{font-si" error: invalid character '<' looking for beginning of value
```

Also figured I'd ask while I'm making an Issue, if I am `decrypting` a key, what is the file I need to provide if I did not encrypt it using `crypt` (or is this not possible)?

`./crypt decrypt azure --vaultURL https://xXxxxXx.vault.azure.net --name name-of-secret`
```
ERROR: expected a pipe stdin
```

**Comment by antoniaklja** [comment]
please make sure your `key` already exists in Azure Key Vault and you specified proper `version`
Apart from that make sure your context is set to proper Azure Subscription - run `az account show`

I'll implement `--subscription` flag anyway to simplify dealing with multiple Azure Subscritpions.

Regarding your second question, I haven't tested it but it should work as long as you can replicate the same decryption mechanism (based on key type in your Key Vault)

**Comment by antoniaklja** [comment]
Azure implementation has been completely re-worked by @tomaszsek. Please re-open in case of any problems.
