### ISSUE TITLE
Version flag doesn't return correct value

### ISSUE THREAD

**Issue by jamesdbloom** [VirtusLab/crypt#13]
The latest release returns the following:

```bash
$ crypt --version
Crypt version 0.0.1
```

The version install via `go get` returns the following:

```bash
$ ~/go/bin/crypt --debug --version
crypt version -
```

**Comment by antoniaklja** [comment]
Please make sure you don't have another `crypt` on your PATH.

```
bartek@thinkpad:~/tmp$ ./crypt --version
crypt version v0.2.1-2a0747e
```

verify
```
which crypt
```

**Comment by pawelprazak** [comment]
I'm afraid this is the same issue as with homebrew, the version is set at compile time in the Makefile, since the go get and homebrew don't use make, it would require a more sophisticated mechanism or some workarounds.

**Comment by pawelprazak** [comment]
Maybe making binary releases more prominent would make this less of an issue, I know it's easy to skip the text about download page.

**Comment by jamesdbloom** [comment]
Your comments make sense because now I have used the downloaded the release version I get the correct version.

```bash
wget https://github.com/VirtusLab/crypt/releases/download/v0.2.1/crypt-darwin-386
chmod +x crypt-darwin-386 
./crypt-darwin-386 --version
```

outputs:

```bash
crypt version v0.2.1-2a0747e
```
