### ISSUE TITLE
distribution packaging [mac - linux]

### ISSUE THREAD

**Issue by styk-tv** [VirtusLab/crypt#8]
As an ops engineer, I frequently lookup crypt and installation page over and over again. It would be great to have `brew install vlcrypt` or `apt-get install vlcrypt` from command line. (or whatever unique name you come up with)

**Comment by antoniaklja** [comment]
thanks @styk-tv, I'll have a look at what we can do.

**Comment by jakubmikusek** [comment]
Hi @styk-tv - as for mac packages you can add VirtusLab tap:
*brew tap virtuslab/cloud*

will update this issue when we have ppa repository set up.

**Comment by pawelprazak** [comment]
@jakubmikusek this one is interesting: https://github.com/goreleaser/goreleaser

**Comment by pawelprazak** [comment]
@jakubmikusek can we close it, is all the work done now?
